// unicode_tables.h — GENERATED by tools/gen_unicode_tables.cpp. DO NOT EDIT.
//
// Unicode version: 17.0.0
// Sources (the first line and the Date: line of each UCD file read):
//   DerivedLineBreak-17.0.0.txt  (2025-07-29, 13:52:13 GMT)
//   DerivedEastAsianWidth-17.0.0.txt  (2025-07-24, 13:28:21 GMT)
//   GraphemeBreakProperty-17.0.0.txt  (2025-06-30, 06:20:23 GMT)
//   WordBreakProperty-17.0.0.txt  (2025-06-30, 06:20:49 GMT)
//   DerivedCoreProperties-17.0.0.txt  (2025-07-30, 23:55:08 GMT)
//   DerivedGeneralCategory-17.0.0.txt  (2025-07-24, 00:12:50 GMT)
//   emoji-data.txt  (2025-07-25, 17:54:31 GMT)
// generator commit: 7002e16f4c2e-dirty
//
// Regenerate:  gen_unicode_tables rolltui/ucd --out rolltui
// Verify:      gen_unicode_tables rolltui/ucd --check rolltui
//              (ctest runs the check; the commit line above is the one line it
//              ignores, since it names the commit the tables were made from)
//
// Each table (defined in unicode_tables.c) is a sorted, non-overlapping list of
// {first, last, value} ranges covering only the code points whose value differs
// from the table's default; look a code point up by binary search on `last`.
// Unassigned code points inside the CJK blocks and Planes 2-3 carry ID / W, and
// the Currency Symbols block PR, from the @missing sub-range lines of the
// Derived* files.
//
// PHASE 14 m5 — ONE TABLE FILE, COMPILED BY BOTH LANGUAGES. The data is C and the
// arrays have C linkage, so the two implementations of the Unicode algorithms
// share them rather than each carrying a copy: 9,800 lines duplicated would be
// 9,800 lines that could disagree, and the whole point of the flag is that the two
// sides answer the SAME tests from the SAME facts.
//
// Each property has two spellings, both generated HERE from one list, because each
// implementation should read naturally in its own language (the m2 rule): plain
// constants for C, an `enum class` for C++. A `static_assert` per value is emitted
// below, so a generator that ever emitted them differently would fail to compile
// rather than silently classify a code point wrong.
#ifndef ROLLTUI_UNICODE_TABLES_H
#define ROLLTUI_UNICODE_TABLES_H
#include <stddef.h>

#include "rolltui/c/rolltui_abi.h"

#ifdef __cplusplus
extern "C" {
#endif

#define ROLLTUI_UNICODE_VERSION "17.0.0"

typedef struct RolltuiUnicodeRange {
  RolltuiCodepoint first;
  RolltuiCodepoint last;
  unsigned char value;
} RolltuiUnicodeRange;

/* LineBreak */
#define ROLLTUI_LINEBREAK_AI 0
#define ROLLTUI_LINEBREAK_AK 1
#define ROLLTUI_LINEBREAK_AL 2
#define ROLLTUI_LINEBREAK_AP 3
#define ROLLTUI_LINEBREAK_AS 4
#define ROLLTUI_LINEBREAK_B2 5
#define ROLLTUI_LINEBREAK_BA 6
#define ROLLTUI_LINEBREAK_BB 7
#define ROLLTUI_LINEBREAK_BK 8
#define ROLLTUI_LINEBREAK_CB 9
#define ROLLTUI_LINEBREAK_CJ 10
#define ROLLTUI_LINEBREAK_CL 11
#define ROLLTUI_LINEBREAK_CM 12
#define ROLLTUI_LINEBREAK_CP 13
#define ROLLTUI_LINEBREAK_CR 14
#define ROLLTUI_LINEBREAK_EB 15
#define ROLLTUI_LINEBREAK_EM 16
#define ROLLTUI_LINEBREAK_EX 17
#define ROLLTUI_LINEBREAK_GL 18
#define ROLLTUI_LINEBREAK_H2 19
#define ROLLTUI_LINEBREAK_H3 20
#define ROLLTUI_LINEBREAK_HH 21
#define ROLLTUI_LINEBREAK_HL 22
#define ROLLTUI_LINEBREAK_HY 23
#define ROLLTUI_LINEBREAK_ID 24
#define ROLLTUI_LINEBREAK_IN 25
#define ROLLTUI_LINEBREAK_IS 26
#define ROLLTUI_LINEBREAK_JL 27
#define ROLLTUI_LINEBREAK_JT 28
#define ROLLTUI_LINEBREAK_JV 29
#define ROLLTUI_LINEBREAK_LF 30
#define ROLLTUI_LINEBREAK_NL 31
#define ROLLTUI_LINEBREAK_NS 32
#define ROLLTUI_LINEBREAK_NU 33
#define ROLLTUI_LINEBREAK_OP 34
#define ROLLTUI_LINEBREAK_PO 35
#define ROLLTUI_LINEBREAK_PR 36
#define ROLLTUI_LINEBREAK_QU 37
#define ROLLTUI_LINEBREAK_RI 38
#define ROLLTUI_LINEBREAK_SA 39
#define ROLLTUI_LINEBREAK_SG 40
#define ROLLTUI_LINEBREAK_SP 41
#define ROLLTUI_LINEBREAK_SY 42
#define ROLLTUI_LINEBREAK_VF 43
#define ROLLTUI_LINEBREAK_VI 44
#define ROLLTUI_LINEBREAK_WJ 45
#define ROLLTUI_LINEBREAK_XX 46
#define ROLLTUI_LINEBREAK_ZW 47
#define ROLLTUI_LINEBREAK_ZWJ 48
#define ROLLTUI_LINEBREAK_DEFAULT ROLLTUI_LINEBREAK_XX

/* EastAsianWidth */
#define ROLLTUI_EASTASIANWIDTH_N 0
#define ROLLTUI_EASTASIANWIDTH_A 1
#define ROLLTUI_EASTASIANWIDTH_F 2
#define ROLLTUI_EASTASIANWIDTH_H 3
#define ROLLTUI_EASTASIANWIDTH_Na 4
#define ROLLTUI_EASTASIANWIDTH_W 5
#define ROLLTUI_EASTASIANWIDTH_DEFAULT ROLLTUI_EASTASIANWIDTH_N

/* GraphemeBreak */
#define ROLLTUI_GRAPHEMEBREAK_Other 0
#define ROLLTUI_GRAPHEMEBREAK_CR 1
#define ROLLTUI_GRAPHEMEBREAK_LF 2
#define ROLLTUI_GRAPHEMEBREAK_Control 3
#define ROLLTUI_GRAPHEMEBREAK_Extend 4
#define ROLLTUI_GRAPHEMEBREAK_ZWJ 5
#define ROLLTUI_GRAPHEMEBREAK_Regional_Indicator 6
#define ROLLTUI_GRAPHEMEBREAK_Prepend 7
#define ROLLTUI_GRAPHEMEBREAK_SpacingMark 8
#define ROLLTUI_GRAPHEMEBREAK_L 9
#define ROLLTUI_GRAPHEMEBREAK_V 10
#define ROLLTUI_GRAPHEMEBREAK_T 11
#define ROLLTUI_GRAPHEMEBREAK_LV 12
#define ROLLTUI_GRAPHEMEBREAK_LVT 13
#define ROLLTUI_GRAPHEMEBREAK_DEFAULT ROLLTUI_GRAPHEMEBREAK_Other

/* WordBreak */
#define ROLLTUI_WORDBREAK_Other 0
#define ROLLTUI_WORDBREAK_CR 1
#define ROLLTUI_WORDBREAK_LF 2
#define ROLLTUI_WORDBREAK_Newline 3
#define ROLLTUI_WORDBREAK_Extend 4
#define ROLLTUI_WORDBREAK_ZWJ 5
#define ROLLTUI_WORDBREAK_Regional_Indicator 6
#define ROLLTUI_WORDBREAK_Format 7
#define ROLLTUI_WORDBREAK_Katakana 8
#define ROLLTUI_WORDBREAK_Hebrew_Letter 9
#define ROLLTUI_WORDBREAK_ALetter 10
#define ROLLTUI_WORDBREAK_Single_Quote 11
#define ROLLTUI_WORDBREAK_Double_Quote 12
#define ROLLTUI_WORDBREAK_MidNumLet 13
#define ROLLTUI_WORDBREAK_MidLetter 14
#define ROLLTUI_WORDBREAK_MidNum 15
#define ROLLTUI_WORDBREAK_Numeric 16
#define ROLLTUI_WORDBREAK_ExtendNumLet 17
#define ROLLTUI_WORDBREAK_WSegSpace 18
#define ROLLTUI_WORDBREAK_DEFAULT ROLLTUI_WORDBREAK_Other

/* IndicConjunctBreak */
#define ROLLTUI_INDICCONJUNCTBREAK_None 0
#define ROLLTUI_INDICCONJUNCTBREAK_Consonant 1
#define ROLLTUI_INDICCONJUNCTBREAK_Extend 2
#define ROLLTUI_INDICCONJUNCTBREAK_Linker 3
#define ROLLTUI_INDICCONJUNCTBREAK_DEFAULT ROLLTUI_INDICCONJUNCTBREAK_None

/* GeneralCategory */
#define ROLLTUI_GENERALCATEGORY_Lu 0
#define ROLLTUI_GENERALCATEGORY_Ll 1
#define ROLLTUI_GENERALCATEGORY_Lt 2
#define ROLLTUI_GENERALCATEGORY_Lm 3
#define ROLLTUI_GENERALCATEGORY_Lo 4
#define ROLLTUI_GENERALCATEGORY_Mn 5
#define ROLLTUI_GENERALCATEGORY_Mc 6
#define ROLLTUI_GENERALCATEGORY_Me 7
#define ROLLTUI_GENERALCATEGORY_Nd 8
#define ROLLTUI_GENERALCATEGORY_Nl 9
#define ROLLTUI_GENERALCATEGORY_No 10
#define ROLLTUI_GENERALCATEGORY_Pc 11
#define ROLLTUI_GENERALCATEGORY_Pd 12
#define ROLLTUI_GENERALCATEGORY_Ps 13
#define ROLLTUI_GENERALCATEGORY_Pe 14
#define ROLLTUI_GENERALCATEGORY_Pi 15
#define ROLLTUI_GENERALCATEGORY_Pf 16
#define ROLLTUI_GENERALCATEGORY_Po 17
#define ROLLTUI_GENERALCATEGORY_Sm 18
#define ROLLTUI_GENERALCATEGORY_Sc 19
#define ROLLTUI_GENERALCATEGORY_Sk 20
#define ROLLTUI_GENERALCATEGORY_So 21
#define ROLLTUI_GENERALCATEGORY_Zs 22
#define ROLLTUI_GENERALCATEGORY_Zl 23
#define ROLLTUI_GENERALCATEGORY_Zp 24
#define ROLLTUI_GENERALCATEGORY_Cc 25
#define ROLLTUI_GENERALCATEGORY_Cf 26
#define ROLLTUI_GENERALCATEGORY_Cs 27
#define ROLLTUI_GENERALCATEGORY_Co 28
#define ROLLTUI_GENERALCATEGORY_Cn 29
#define ROLLTUI_GENERALCATEGORY_DEFAULT ROLLTUI_GENERALCATEGORY_Cn

extern const RolltuiUnicodeRange rolltui_u_line_break[2917];  /* LineBreak */
#define ROLLTUI_U_LINE_BREAK_COUNT 2917
extern const RolltuiUnicodeRange rolltui_u_east_asian_width[318];  /* EastAsianWidth */
#define ROLLTUI_U_EAST_ASIAN_WIDTH_COUNT 318
extern const RolltuiUnicodeRange rolltui_u_grapheme_break[1386];  /* GraphemeBreak */
#define ROLLTUI_U_GRAPHEME_BREAK_COUNT 1386
extern const RolltuiUnicodeRange rolltui_u_word_break[1100];  /* WordBreak */
#define ROLLTUI_U_WORD_BREAK_COUNT 1100
extern const RolltuiUnicodeRange rolltui_u_indic_conjunct_break[473];  /* IndicConjunctBreak */
#define ROLLTUI_U_INDIC_CONJUNCT_BREAK_COUNT 473
extern const RolltuiUnicodeRange rolltui_u_general_category[3409];  /* GeneralCategory */
#define ROLLTUI_U_GENERAL_CATEGORY_COUNT 3409
extern const RolltuiUnicodeRange rolltui_u_extended_pictographic[156];  /* ExtendedPictographic (value 1 = Yes; absent = No) */
#define ROLLTUI_U_EXTENDED_PICTOGRAPHIC_COUNT 156
extern const RolltuiUnicodeRange rolltui_u_default_ignorable[17];  /* DefaultIgnorable (value 1 = Yes; absent = No) */
#define ROLLTUI_U_DEFAULT_IGNORABLE_COUNT 17

#ifdef __cplusplus
}  /* extern "C" */

// The C++ spelling of the same facts. The arrays are the C arrays under their old
// names, so `UnicodeCpp.cpp` reads exactly as it always did.
namespace rolltui::unicode {

inline constexpr char kUnicodeVersion[] = ROLLTUI_UNICODE_VERSION;
using Range = RolltuiUnicodeRange;

enum class LineBreak : unsigned char { AI, AK, AL, AP, AS, B2, BA, BB, BK, CB, CJ, CL, CM, CP, CR, EB, EM, EX, GL, H2, H3, HH, HL, HY, ID, IN, IS, JL, JT, JV, LF, NL, NS, NU, OP, PO, PR, QU, RI, SA, SG, SP, SY, VF, VI, WJ, XX, ZW, ZWJ };
static_assert(static_cast<unsigned>(LineBreak::AI) == ROLLTUI_LINEBREAK_AI, "LineBreak::AI and ROLLTUI_LINEBREAK_AI disagree");
static_assert(static_cast<unsigned>(LineBreak::AK) == ROLLTUI_LINEBREAK_AK, "LineBreak::AK and ROLLTUI_LINEBREAK_AK disagree");
static_assert(static_cast<unsigned>(LineBreak::AL) == ROLLTUI_LINEBREAK_AL, "LineBreak::AL and ROLLTUI_LINEBREAK_AL disagree");
static_assert(static_cast<unsigned>(LineBreak::AP) == ROLLTUI_LINEBREAK_AP, "LineBreak::AP and ROLLTUI_LINEBREAK_AP disagree");
static_assert(static_cast<unsigned>(LineBreak::AS) == ROLLTUI_LINEBREAK_AS, "LineBreak::AS and ROLLTUI_LINEBREAK_AS disagree");
static_assert(static_cast<unsigned>(LineBreak::B2) == ROLLTUI_LINEBREAK_B2, "LineBreak::B2 and ROLLTUI_LINEBREAK_B2 disagree");
static_assert(static_cast<unsigned>(LineBreak::BA) == ROLLTUI_LINEBREAK_BA, "LineBreak::BA and ROLLTUI_LINEBREAK_BA disagree");
static_assert(static_cast<unsigned>(LineBreak::BB) == ROLLTUI_LINEBREAK_BB, "LineBreak::BB and ROLLTUI_LINEBREAK_BB disagree");
static_assert(static_cast<unsigned>(LineBreak::BK) == ROLLTUI_LINEBREAK_BK, "LineBreak::BK and ROLLTUI_LINEBREAK_BK disagree");
static_assert(static_cast<unsigned>(LineBreak::CB) == ROLLTUI_LINEBREAK_CB, "LineBreak::CB and ROLLTUI_LINEBREAK_CB disagree");
static_assert(static_cast<unsigned>(LineBreak::CJ) == ROLLTUI_LINEBREAK_CJ, "LineBreak::CJ and ROLLTUI_LINEBREAK_CJ disagree");
static_assert(static_cast<unsigned>(LineBreak::CL) == ROLLTUI_LINEBREAK_CL, "LineBreak::CL and ROLLTUI_LINEBREAK_CL disagree");
static_assert(static_cast<unsigned>(LineBreak::CM) == ROLLTUI_LINEBREAK_CM, "LineBreak::CM and ROLLTUI_LINEBREAK_CM disagree");
static_assert(static_cast<unsigned>(LineBreak::CP) == ROLLTUI_LINEBREAK_CP, "LineBreak::CP and ROLLTUI_LINEBREAK_CP disagree");
static_assert(static_cast<unsigned>(LineBreak::CR) == ROLLTUI_LINEBREAK_CR, "LineBreak::CR and ROLLTUI_LINEBREAK_CR disagree");
static_assert(static_cast<unsigned>(LineBreak::EB) == ROLLTUI_LINEBREAK_EB, "LineBreak::EB and ROLLTUI_LINEBREAK_EB disagree");
static_assert(static_cast<unsigned>(LineBreak::EM) == ROLLTUI_LINEBREAK_EM, "LineBreak::EM and ROLLTUI_LINEBREAK_EM disagree");
static_assert(static_cast<unsigned>(LineBreak::EX) == ROLLTUI_LINEBREAK_EX, "LineBreak::EX and ROLLTUI_LINEBREAK_EX disagree");
static_assert(static_cast<unsigned>(LineBreak::GL) == ROLLTUI_LINEBREAK_GL, "LineBreak::GL and ROLLTUI_LINEBREAK_GL disagree");
static_assert(static_cast<unsigned>(LineBreak::H2) == ROLLTUI_LINEBREAK_H2, "LineBreak::H2 and ROLLTUI_LINEBREAK_H2 disagree");
static_assert(static_cast<unsigned>(LineBreak::H3) == ROLLTUI_LINEBREAK_H3, "LineBreak::H3 and ROLLTUI_LINEBREAK_H3 disagree");
static_assert(static_cast<unsigned>(LineBreak::HH) == ROLLTUI_LINEBREAK_HH, "LineBreak::HH and ROLLTUI_LINEBREAK_HH disagree");
static_assert(static_cast<unsigned>(LineBreak::HL) == ROLLTUI_LINEBREAK_HL, "LineBreak::HL and ROLLTUI_LINEBREAK_HL disagree");
static_assert(static_cast<unsigned>(LineBreak::HY) == ROLLTUI_LINEBREAK_HY, "LineBreak::HY and ROLLTUI_LINEBREAK_HY disagree");
static_assert(static_cast<unsigned>(LineBreak::ID) == ROLLTUI_LINEBREAK_ID, "LineBreak::ID and ROLLTUI_LINEBREAK_ID disagree");
static_assert(static_cast<unsigned>(LineBreak::IN) == ROLLTUI_LINEBREAK_IN, "LineBreak::IN and ROLLTUI_LINEBREAK_IN disagree");
static_assert(static_cast<unsigned>(LineBreak::IS) == ROLLTUI_LINEBREAK_IS, "LineBreak::IS and ROLLTUI_LINEBREAK_IS disagree");
static_assert(static_cast<unsigned>(LineBreak::JL) == ROLLTUI_LINEBREAK_JL, "LineBreak::JL and ROLLTUI_LINEBREAK_JL disagree");
static_assert(static_cast<unsigned>(LineBreak::JT) == ROLLTUI_LINEBREAK_JT, "LineBreak::JT and ROLLTUI_LINEBREAK_JT disagree");
static_assert(static_cast<unsigned>(LineBreak::JV) == ROLLTUI_LINEBREAK_JV, "LineBreak::JV and ROLLTUI_LINEBREAK_JV disagree");
static_assert(static_cast<unsigned>(LineBreak::LF) == ROLLTUI_LINEBREAK_LF, "LineBreak::LF and ROLLTUI_LINEBREAK_LF disagree");
static_assert(static_cast<unsigned>(LineBreak::NL) == ROLLTUI_LINEBREAK_NL, "LineBreak::NL and ROLLTUI_LINEBREAK_NL disagree");
static_assert(static_cast<unsigned>(LineBreak::NS) == ROLLTUI_LINEBREAK_NS, "LineBreak::NS and ROLLTUI_LINEBREAK_NS disagree");
static_assert(static_cast<unsigned>(LineBreak::NU) == ROLLTUI_LINEBREAK_NU, "LineBreak::NU and ROLLTUI_LINEBREAK_NU disagree");
static_assert(static_cast<unsigned>(LineBreak::OP) == ROLLTUI_LINEBREAK_OP, "LineBreak::OP and ROLLTUI_LINEBREAK_OP disagree");
static_assert(static_cast<unsigned>(LineBreak::PO) == ROLLTUI_LINEBREAK_PO, "LineBreak::PO and ROLLTUI_LINEBREAK_PO disagree");
static_assert(static_cast<unsigned>(LineBreak::PR) == ROLLTUI_LINEBREAK_PR, "LineBreak::PR and ROLLTUI_LINEBREAK_PR disagree");
static_assert(static_cast<unsigned>(LineBreak::QU) == ROLLTUI_LINEBREAK_QU, "LineBreak::QU and ROLLTUI_LINEBREAK_QU disagree");
static_assert(static_cast<unsigned>(LineBreak::RI) == ROLLTUI_LINEBREAK_RI, "LineBreak::RI and ROLLTUI_LINEBREAK_RI disagree");
static_assert(static_cast<unsigned>(LineBreak::SA) == ROLLTUI_LINEBREAK_SA, "LineBreak::SA and ROLLTUI_LINEBREAK_SA disagree");
static_assert(static_cast<unsigned>(LineBreak::SG) == ROLLTUI_LINEBREAK_SG, "LineBreak::SG and ROLLTUI_LINEBREAK_SG disagree");
static_assert(static_cast<unsigned>(LineBreak::SP) == ROLLTUI_LINEBREAK_SP, "LineBreak::SP and ROLLTUI_LINEBREAK_SP disagree");
static_assert(static_cast<unsigned>(LineBreak::SY) == ROLLTUI_LINEBREAK_SY, "LineBreak::SY and ROLLTUI_LINEBREAK_SY disagree");
static_assert(static_cast<unsigned>(LineBreak::VF) == ROLLTUI_LINEBREAK_VF, "LineBreak::VF and ROLLTUI_LINEBREAK_VF disagree");
static_assert(static_cast<unsigned>(LineBreak::VI) == ROLLTUI_LINEBREAK_VI, "LineBreak::VI and ROLLTUI_LINEBREAK_VI disagree");
static_assert(static_cast<unsigned>(LineBreak::WJ) == ROLLTUI_LINEBREAK_WJ, "LineBreak::WJ and ROLLTUI_LINEBREAK_WJ disagree");
static_assert(static_cast<unsigned>(LineBreak::XX) == ROLLTUI_LINEBREAK_XX, "LineBreak::XX and ROLLTUI_LINEBREAK_XX disagree");
static_assert(static_cast<unsigned>(LineBreak::ZW) == ROLLTUI_LINEBREAK_ZW, "LineBreak::ZW and ROLLTUI_LINEBREAK_ZW disagree");
static_assert(static_cast<unsigned>(LineBreak::ZWJ) == ROLLTUI_LINEBREAK_ZWJ, "LineBreak::ZWJ and ROLLTUI_LINEBREAK_ZWJ disagree");
inline constexpr LineBreak kLineBreakDefault = LineBreak::XX;

enum class EastAsianWidth : unsigned char { N, A, F, H, Na, W };
static_assert(static_cast<unsigned>(EastAsianWidth::N) == ROLLTUI_EASTASIANWIDTH_N, "EastAsianWidth::N and ROLLTUI_EASTASIANWIDTH_N disagree");
static_assert(static_cast<unsigned>(EastAsianWidth::A) == ROLLTUI_EASTASIANWIDTH_A, "EastAsianWidth::A and ROLLTUI_EASTASIANWIDTH_A disagree");
static_assert(static_cast<unsigned>(EastAsianWidth::F) == ROLLTUI_EASTASIANWIDTH_F, "EastAsianWidth::F and ROLLTUI_EASTASIANWIDTH_F disagree");
static_assert(static_cast<unsigned>(EastAsianWidth::H) == ROLLTUI_EASTASIANWIDTH_H, "EastAsianWidth::H and ROLLTUI_EASTASIANWIDTH_H disagree");
static_assert(static_cast<unsigned>(EastAsianWidth::Na) == ROLLTUI_EASTASIANWIDTH_Na, "EastAsianWidth::Na and ROLLTUI_EASTASIANWIDTH_Na disagree");
static_assert(static_cast<unsigned>(EastAsianWidth::W) == ROLLTUI_EASTASIANWIDTH_W, "EastAsianWidth::W and ROLLTUI_EASTASIANWIDTH_W disagree");
inline constexpr EastAsianWidth kEastAsianWidthDefault = EastAsianWidth::N;

enum class GraphemeBreak : unsigned char { Other, CR, LF, Control, Extend, ZWJ, Regional_Indicator, Prepend, SpacingMark, L, V, T, LV, LVT };
static_assert(static_cast<unsigned>(GraphemeBreak::Other) == ROLLTUI_GRAPHEMEBREAK_Other, "GraphemeBreak::Other and ROLLTUI_GRAPHEMEBREAK_Other disagree");
static_assert(static_cast<unsigned>(GraphemeBreak::CR) == ROLLTUI_GRAPHEMEBREAK_CR, "GraphemeBreak::CR and ROLLTUI_GRAPHEMEBREAK_CR disagree");
static_assert(static_cast<unsigned>(GraphemeBreak::LF) == ROLLTUI_GRAPHEMEBREAK_LF, "GraphemeBreak::LF and ROLLTUI_GRAPHEMEBREAK_LF disagree");
static_assert(static_cast<unsigned>(GraphemeBreak::Control) == ROLLTUI_GRAPHEMEBREAK_Control, "GraphemeBreak::Control and ROLLTUI_GRAPHEMEBREAK_Control disagree");
static_assert(static_cast<unsigned>(GraphemeBreak::Extend) == ROLLTUI_GRAPHEMEBREAK_Extend, "GraphemeBreak::Extend and ROLLTUI_GRAPHEMEBREAK_Extend disagree");
static_assert(static_cast<unsigned>(GraphemeBreak::ZWJ) == ROLLTUI_GRAPHEMEBREAK_ZWJ, "GraphemeBreak::ZWJ and ROLLTUI_GRAPHEMEBREAK_ZWJ disagree");
static_assert(static_cast<unsigned>(GraphemeBreak::Regional_Indicator) == ROLLTUI_GRAPHEMEBREAK_Regional_Indicator, "GraphemeBreak::Regional_Indicator and ROLLTUI_GRAPHEMEBREAK_Regional_Indicator disagree");
static_assert(static_cast<unsigned>(GraphemeBreak::Prepend) == ROLLTUI_GRAPHEMEBREAK_Prepend, "GraphemeBreak::Prepend and ROLLTUI_GRAPHEMEBREAK_Prepend disagree");
static_assert(static_cast<unsigned>(GraphemeBreak::SpacingMark) == ROLLTUI_GRAPHEMEBREAK_SpacingMark, "GraphemeBreak::SpacingMark and ROLLTUI_GRAPHEMEBREAK_SpacingMark disagree");
static_assert(static_cast<unsigned>(GraphemeBreak::L) == ROLLTUI_GRAPHEMEBREAK_L, "GraphemeBreak::L and ROLLTUI_GRAPHEMEBREAK_L disagree");
static_assert(static_cast<unsigned>(GraphemeBreak::V) == ROLLTUI_GRAPHEMEBREAK_V, "GraphemeBreak::V and ROLLTUI_GRAPHEMEBREAK_V disagree");
static_assert(static_cast<unsigned>(GraphemeBreak::T) == ROLLTUI_GRAPHEMEBREAK_T, "GraphemeBreak::T and ROLLTUI_GRAPHEMEBREAK_T disagree");
static_assert(static_cast<unsigned>(GraphemeBreak::LV) == ROLLTUI_GRAPHEMEBREAK_LV, "GraphemeBreak::LV and ROLLTUI_GRAPHEMEBREAK_LV disagree");
static_assert(static_cast<unsigned>(GraphemeBreak::LVT) == ROLLTUI_GRAPHEMEBREAK_LVT, "GraphemeBreak::LVT and ROLLTUI_GRAPHEMEBREAK_LVT disagree");
inline constexpr GraphemeBreak kGraphemeBreakDefault = GraphemeBreak::Other;

enum class WordBreak : unsigned char { Other, CR, LF, Newline, Extend, ZWJ, Regional_Indicator, Format, Katakana, Hebrew_Letter, ALetter, Single_Quote, Double_Quote, MidNumLet, MidLetter, MidNum, Numeric, ExtendNumLet, WSegSpace };
static_assert(static_cast<unsigned>(WordBreak::Other) == ROLLTUI_WORDBREAK_Other, "WordBreak::Other and ROLLTUI_WORDBREAK_Other disagree");
static_assert(static_cast<unsigned>(WordBreak::CR) == ROLLTUI_WORDBREAK_CR, "WordBreak::CR and ROLLTUI_WORDBREAK_CR disagree");
static_assert(static_cast<unsigned>(WordBreak::LF) == ROLLTUI_WORDBREAK_LF, "WordBreak::LF and ROLLTUI_WORDBREAK_LF disagree");
static_assert(static_cast<unsigned>(WordBreak::Newline) == ROLLTUI_WORDBREAK_Newline, "WordBreak::Newline and ROLLTUI_WORDBREAK_Newline disagree");
static_assert(static_cast<unsigned>(WordBreak::Extend) == ROLLTUI_WORDBREAK_Extend, "WordBreak::Extend and ROLLTUI_WORDBREAK_Extend disagree");
static_assert(static_cast<unsigned>(WordBreak::ZWJ) == ROLLTUI_WORDBREAK_ZWJ, "WordBreak::ZWJ and ROLLTUI_WORDBREAK_ZWJ disagree");
static_assert(static_cast<unsigned>(WordBreak::Regional_Indicator) == ROLLTUI_WORDBREAK_Regional_Indicator, "WordBreak::Regional_Indicator and ROLLTUI_WORDBREAK_Regional_Indicator disagree");
static_assert(static_cast<unsigned>(WordBreak::Format) == ROLLTUI_WORDBREAK_Format, "WordBreak::Format and ROLLTUI_WORDBREAK_Format disagree");
static_assert(static_cast<unsigned>(WordBreak::Katakana) == ROLLTUI_WORDBREAK_Katakana, "WordBreak::Katakana and ROLLTUI_WORDBREAK_Katakana disagree");
static_assert(static_cast<unsigned>(WordBreak::Hebrew_Letter) == ROLLTUI_WORDBREAK_Hebrew_Letter, "WordBreak::Hebrew_Letter and ROLLTUI_WORDBREAK_Hebrew_Letter disagree");
static_assert(static_cast<unsigned>(WordBreak::ALetter) == ROLLTUI_WORDBREAK_ALetter, "WordBreak::ALetter and ROLLTUI_WORDBREAK_ALetter disagree");
static_assert(static_cast<unsigned>(WordBreak::Single_Quote) == ROLLTUI_WORDBREAK_Single_Quote, "WordBreak::Single_Quote and ROLLTUI_WORDBREAK_Single_Quote disagree");
static_assert(static_cast<unsigned>(WordBreak::Double_Quote) == ROLLTUI_WORDBREAK_Double_Quote, "WordBreak::Double_Quote and ROLLTUI_WORDBREAK_Double_Quote disagree");
static_assert(static_cast<unsigned>(WordBreak::MidNumLet) == ROLLTUI_WORDBREAK_MidNumLet, "WordBreak::MidNumLet and ROLLTUI_WORDBREAK_MidNumLet disagree");
static_assert(static_cast<unsigned>(WordBreak::MidLetter) == ROLLTUI_WORDBREAK_MidLetter, "WordBreak::MidLetter and ROLLTUI_WORDBREAK_MidLetter disagree");
static_assert(static_cast<unsigned>(WordBreak::MidNum) == ROLLTUI_WORDBREAK_MidNum, "WordBreak::MidNum and ROLLTUI_WORDBREAK_MidNum disagree");
static_assert(static_cast<unsigned>(WordBreak::Numeric) == ROLLTUI_WORDBREAK_Numeric, "WordBreak::Numeric and ROLLTUI_WORDBREAK_Numeric disagree");
static_assert(static_cast<unsigned>(WordBreak::ExtendNumLet) == ROLLTUI_WORDBREAK_ExtendNumLet, "WordBreak::ExtendNumLet and ROLLTUI_WORDBREAK_ExtendNumLet disagree");
static_assert(static_cast<unsigned>(WordBreak::WSegSpace) == ROLLTUI_WORDBREAK_WSegSpace, "WordBreak::WSegSpace and ROLLTUI_WORDBREAK_WSegSpace disagree");
inline constexpr WordBreak kWordBreakDefault = WordBreak::Other;

enum class IndicConjunctBreak : unsigned char { None, Consonant, Extend, Linker };
static_assert(static_cast<unsigned>(IndicConjunctBreak::None) == ROLLTUI_INDICCONJUNCTBREAK_None, "IndicConjunctBreak::None and ROLLTUI_INDICCONJUNCTBREAK_None disagree");
static_assert(static_cast<unsigned>(IndicConjunctBreak::Consonant) == ROLLTUI_INDICCONJUNCTBREAK_Consonant, "IndicConjunctBreak::Consonant and ROLLTUI_INDICCONJUNCTBREAK_Consonant disagree");
static_assert(static_cast<unsigned>(IndicConjunctBreak::Extend) == ROLLTUI_INDICCONJUNCTBREAK_Extend, "IndicConjunctBreak::Extend and ROLLTUI_INDICCONJUNCTBREAK_Extend disagree");
static_assert(static_cast<unsigned>(IndicConjunctBreak::Linker) == ROLLTUI_INDICCONJUNCTBREAK_Linker, "IndicConjunctBreak::Linker and ROLLTUI_INDICCONJUNCTBREAK_Linker disagree");
inline constexpr IndicConjunctBreak kIndicConjunctBreakDefault = IndicConjunctBreak::None;

enum class GeneralCategory : unsigned char { Lu, Ll, Lt, Lm, Lo, Mn, Mc, Me, Nd, Nl, No, Pc, Pd, Ps, Pe, Pi, Pf, Po, Sm, Sc, Sk, So, Zs, Zl, Zp, Cc, Cf, Cs, Co, Cn };
static_assert(static_cast<unsigned>(GeneralCategory::Lu) == ROLLTUI_GENERALCATEGORY_Lu, "GeneralCategory::Lu and ROLLTUI_GENERALCATEGORY_Lu disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Ll) == ROLLTUI_GENERALCATEGORY_Ll, "GeneralCategory::Ll and ROLLTUI_GENERALCATEGORY_Ll disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Lt) == ROLLTUI_GENERALCATEGORY_Lt, "GeneralCategory::Lt and ROLLTUI_GENERALCATEGORY_Lt disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Lm) == ROLLTUI_GENERALCATEGORY_Lm, "GeneralCategory::Lm and ROLLTUI_GENERALCATEGORY_Lm disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Lo) == ROLLTUI_GENERALCATEGORY_Lo, "GeneralCategory::Lo and ROLLTUI_GENERALCATEGORY_Lo disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Mn) == ROLLTUI_GENERALCATEGORY_Mn, "GeneralCategory::Mn and ROLLTUI_GENERALCATEGORY_Mn disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Mc) == ROLLTUI_GENERALCATEGORY_Mc, "GeneralCategory::Mc and ROLLTUI_GENERALCATEGORY_Mc disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Me) == ROLLTUI_GENERALCATEGORY_Me, "GeneralCategory::Me and ROLLTUI_GENERALCATEGORY_Me disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Nd) == ROLLTUI_GENERALCATEGORY_Nd, "GeneralCategory::Nd and ROLLTUI_GENERALCATEGORY_Nd disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Nl) == ROLLTUI_GENERALCATEGORY_Nl, "GeneralCategory::Nl and ROLLTUI_GENERALCATEGORY_Nl disagree");
static_assert(static_cast<unsigned>(GeneralCategory::No) == ROLLTUI_GENERALCATEGORY_No, "GeneralCategory::No and ROLLTUI_GENERALCATEGORY_No disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Pc) == ROLLTUI_GENERALCATEGORY_Pc, "GeneralCategory::Pc and ROLLTUI_GENERALCATEGORY_Pc disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Pd) == ROLLTUI_GENERALCATEGORY_Pd, "GeneralCategory::Pd and ROLLTUI_GENERALCATEGORY_Pd disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Ps) == ROLLTUI_GENERALCATEGORY_Ps, "GeneralCategory::Ps and ROLLTUI_GENERALCATEGORY_Ps disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Pe) == ROLLTUI_GENERALCATEGORY_Pe, "GeneralCategory::Pe and ROLLTUI_GENERALCATEGORY_Pe disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Pi) == ROLLTUI_GENERALCATEGORY_Pi, "GeneralCategory::Pi and ROLLTUI_GENERALCATEGORY_Pi disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Pf) == ROLLTUI_GENERALCATEGORY_Pf, "GeneralCategory::Pf and ROLLTUI_GENERALCATEGORY_Pf disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Po) == ROLLTUI_GENERALCATEGORY_Po, "GeneralCategory::Po and ROLLTUI_GENERALCATEGORY_Po disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Sm) == ROLLTUI_GENERALCATEGORY_Sm, "GeneralCategory::Sm and ROLLTUI_GENERALCATEGORY_Sm disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Sc) == ROLLTUI_GENERALCATEGORY_Sc, "GeneralCategory::Sc and ROLLTUI_GENERALCATEGORY_Sc disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Sk) == ROLLTUI_GENERALCATEGORY_Sk, "GeneralCategory::Sk and ROLLTUI_GENERALCATEGORY_Sk disagree");
static_assert(static_cast<unsigned>(GeneralCategory::So) == ROLLTUI_GENERALCATEGORY_So, "GeneralCategory::So and ROLLTUI_GENERALCATEGORY_So disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Zs) == ROLLTUI_GENERALCATEGORY_Zs, "GeneralCategory::Zs and ROLLTUI_GENERALCATEGORY_Zs disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Zl) == ROLLTUI_GENERALCATEGORY_Zl, "GeneralCategory::Zl and ROLLTUI_GENERALCATEGORY_Zl disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Zp) == ROLLTUI_GENERALCATEGORY_Zp, "GeneralCategory::Zp and ROLLTUI_GENERALCATEGORY_Zp disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Cc) == ROLLTUI_GENERALCATEGORY_Cc, "GeneralCategory::Cc and ROLLTUI_GENERALCATEGORY_Cc disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Cf) == ROLLTUI_GENERALCATEGORY_Cf, "GeneralCategory::Cf and ROLLTUI_GENERALCATEGORY_Cf disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Cs) == ROLLTUI_GENERALCATEGORY_Cs, "GeneralCategory::Cs and ROLLTUI_GENERALCATEGORY_Cs disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Co) == ROLLTUI_GENERALCATEGORY_Co, "GeneralCategory::Co and ROLLTUI_GENERALCATEGORY_Co disagree");
static_assert(static_cast<unsigned>(GeneralCategory::Cn) == ROLLTUI_GENERALCATEGORY_Cn, "GeneralCategory::Cn and ROLLTUI_GENERALCATEGORY_Cn disagree");
inline constexpr GeneralCategory kGeneralCategoryDefault = GeneralCategory::Cn;

inline const Range* const kLineBreak = rolltui_u_line_break;
inline constexpr std::size_t kLineBreakCount = ROLLTUI_U_LINE_BREAK_COUNT;
inline const Range* const kEastAsianWidth = rolltui_u_east_asian_width;
inline constexpr std::size_t kEastAsianWidthCount = ROLLTUI_U_EAST_ASIAN_WIDTH_COUNT;
inline const Range* const kGraphemeBreak = rolltui_u_grapheme_break;
inline constexpr std::size_t kGraphemeBreakCount = ROLLTUI_U_GRAPHEME_BREAK_COUNT;
inline const Range* const kWordBreak = rolltui_u_word_break;
inline constexpr std::size_t kWordBreakCount = ROLLTUI_U_WORD_BREAK_COUNT;
inline const Range* const kIndicConjunctBreak = rolltui_u_indic_conjunct_break;
inline constexpr std::size_t kIndicConjunctBreakCount = ROLLTUI_U_INDIC_CONJUNCT_BREAK_COUNT;
inline const Range* const kGeneralCategory = rolltui_u_general_category;
inline constexpr std::size_t kGeneralCategoryCount = ROLLTUI_U_GENERAL_CATEGORY_COUNT;
inline const Range* const kExtendedPictographic = rolltui_u_extended_pictographic;
inline constexpr std::size_t kExtendedPictographicCount = ROLLTUI_U_EXTENDED_PICTOGRAPHIC_COUNT;
inline const Range* const kDefaultIgnorable = rolltui_u_default_ignorable;
inline constexpr std::size_t kDefaultIgnorableCount = ROLLTUI_U_DEFAULT_IGNORABLE_COUNT;

}  // namespace rolltui::unicode
#endif  // __cplusplus

#endif  /* ROLLTUI_UNICODE_TABLES_H */
