// unicode_tables.hpp — GENERATED by tools/gen_unicode_tables.cpp. DO NOT EDIT.
//
// Unicode version: 17.0.0
// Sources (the first line and the Date: line of each UCD file read):
//   DerivedLineBreak-17.0.0.txt  (2025-07-29, 13:52:13 GMT)
//   DerivedEastAsianWidth-17.0.0.txt  (2025-07-24, 13:28:21 GMT)
//   GraphemeBreakProperty-17.0.0.txt  (2025-06-30, 06:20:23 GMT)
//   WordBreakProperty-17.0.0.txt  (2025-06-30, 06:20:49 GMT)
//   DerivedCoreProperties-17.0.0.txt  (2025-07-30, 23:55:08 GMT)
//   DerivedGeneralCategory-17.0.0.txt  (2025-07-24, 00:12:50 GMT)
//   emoji-data.txt  (2025-07-25, 17:54:31 GMT)
// generator commit: e7c92a60f32a-dirty
//
// Regenerate:  gen_unicode_tables rolltui/ucd --out rolltui
// Verify:      gen_unicode_tables rolltui/ucd --check rolltui
//              (ctest runs the check; the commit line above is the one line it
//              ignores, since it names the commit the tables were made from)
//
// Each table (defined in unicode_tables.cpp) is a sorted, non-overlapping list
// of {first, last, value} ranges covering only the code points whose value
// differs from the table's default; look a code point up by binary search on
// `last` (rolltui/Unicode.hpp does). Unassigned code points inside the CJK
// blocks and Planes 2-3 carry ID / W, and the Currency Symbols block PR, from
// the @missing sub-range lines of the Derived* files.
#pragma once
#include <cstddef>
#include <cstdint>

namespace rolltui::unicode {

inline constexpr char kUnicodeVersion[] = "17.0.0";

struct Range {
  char32_t first;
  char32_t last;
  std::uint8_t value;
};

enum class LineBreak : std::uint8_t { AI, AK, AL, AP, AS, B2, BA, BB, BK, CB, CJ, CL, CM, CP, CR, EB, EM, EX, GL, H2, H3, HH, HL, HY, ID, IN, IS, JL, JT, JV, LF, NL, NS, NU, OP, PO, PR, QU, RI, SA, SG, SP, SY, VF, VI, WJ, XX, ZW, ZWJ };
inline constexpr LineBreak kLineBreakDefault = LineBreak::XX;

enum class EastAsianWidth : std::uint8_t { N, A, F, H, Na, W };
inline constexpr EastAsianWidth kEastAsianWidthDefault = EastAsianWidth::N;

enum class GraphemeBreak : std::uint8_t { Other, CR, LF, Control, Extend, ZWJ, Regional_Indicator, Prepend, SpacingMark, L, V, T, LV, LVT };
inline constexpr GraphemeBreak kGraphemeBreakDefault = GraphemeBreak::Other;

enum class WordBreak : std::uint8_t { Other, CR, LF, Newline, Extend, ZWJ, Regional_Indicator, Format, Katakana, Hebrew_Letter, ALetter, Single_Quote, Double_Quote, MidNumLet, MidLetter, MidNum, Numeric, ExtendNumLet, WSegSpace };
inline constexpr WordBreak kWordBreakDefault = WordBreak::Other;

enum class IndicConjunctBreak : std::uint8_t { None, Consonant, Extend, Linker };
inline constexpr IndicConjunctBreak kIndicConjunctBreakDefault = IndicConjunctBreak::None;

enum class GeneralCategory : std::uint8_t { Lu, Ll, Lt, Lm, Lo, Mn, Mc, Me, Nd, Nl, No, Pc, Pd, Ps, Pe, Pi, Pf, Po, Sm, Sc, Sk, So, Zs, Zl, Zp, Cc, Cf, Cs, Co, Cn };
inline constexpr GeneralCategory kGeneralCategoryDefault = GeneralCategory::Cn;

extern const Range kLineBreak[2917];  // LineBreak
inline constexpr std::size_t kLineBreakCount = 2917;
extern const Range kEastAsianWidth[318];  // EastAsianWidth
inline constexpr std::size_t kEastAsianWidthCount = 318;
extern const Range kGraphemeBreak[1386];  // GraphemeBreak
inline constexpr std::size_t kGraphemeBreakCount = 1386;
extern const Range kWordBreak[1100];  // WordBreak
inline constexpr std::size_t kWordBreakCount = 1100;
extern const Range kIndicConjunctBreak[473];  // IndicConjunctBreak
inline constexpr std::size_t kIndicConjunctBreakCount = 473;
extern const Range kGeneralCategory[3409];  // GeneralCategory
inline constexpr std::size_t kGeneralCategoryCount = 3409;
extern const Range kExtendedPictographic[156];  // ExtendedPictographic (value 1 = Yes; absent = No)
inline constexpr std::size_t kExtendedPictographicCount = 156;
extern const Range kDefaultIgnorable[17];  // DefaultIgnorable (value 1 = Yes; absent = No)
inline constexpr std::size_t kDefaultIgnorableCount = 17;

}  // namespace rolltui::unicode
