# embed_presets.cmake — writes a C++ source embedding every file in FILES as a
# (name, contents) table, so the presets that SHIP are real files in the source tree
# (rolltui/presets/) that the editor may write, and are compiled in and parsed at
# start like the built-in layouts (plan/phase-9.md m11e, rule 5).
#
#   cmake -DOUT=<generated.cpp> -DTABLE=kThemePresets "-DFILES=<a.json;b.json>" -P embed_presets.cmake
# TABLE names the generated array (kThemePresets, kBindingsPresets); its count is
# <TABLE>Count with the trailing "s" dropped (kThemePresetCount).
#
string(REGEX REPLACE "s$" "" COUNT_NAME "${TABLE}")
file(WRITE "${OUT}"
  "// generated by rolltui/cmake/embed_presets.cmake from rolltui/presets/ — do not edit\n"
  "#include <cstddef>\n#include <string_view>\n#include <utility>\n\n"
  "namespace rolltui::embedded {\n\n"
  "extern const std::pair<std::string_view, std::string_view> ${TABLE}[];\n"
  "extern const std::size_t ${COUNT_NAME}Count;\n\n"
  "const std::pair<std::string_view, std::string_view> ${TABLE}[] = {\n")
foreach(f IN LISTS FILES)
  get_filename_component(name "${f}" NAME_WE)
  file(READ "${f}" content)
  file(APPEND "${OUT}" "  {\"${name}\", R\"__json__(${content})__json__\"},\n")
endforeach()
file(APPEND "${OUT}"
  "};\nconst std::size_t ${COUNT_NAME}Count = sizeof ${TABLE} / sizeof ${TABLE}[0];\n\n"
  "}  // namespace rolltui::embedded\n")
