# embed_presets.cmake — writes a C++ source embedding every file in FILES as a
# (name, contents) table, so the presets that SHIP are real files in the source tree
# (rolltui/presets/) that the editor may write, and are compiled in and parsed at
# start like the built-in layouts (plan/phase-9.md m11e, rule 5).
#
#   cmake -DOUT=<generated.cpp> "-DFILES=<a.json;b.json>" -P embed_presets.cmake
#
file(WRITE "${OUT}"
  "// generated by rolltui/cmake/embed_presets.cmake from rolltui/presets/themes/*.json — do not edit\n"
  "#include <cstddef>\n#include <string_view>\n#include <utility>\n\n"
  "namespace rolltui::embedded {\n\n"
  "extern const std::pair<std::string_view, std::string_view> kThemePresets[];\n"
  "extern const std::size_t kThemePresetCount;\n\n"
  "const std::pair<std::string_view, std::string_view> kThemePresets[] = {\n")
foreach(f IN LISTS FILES)
  get_filename_component(name "${f}" NAME_WE)
  file(READ "${f}" content)
  file(APPEND "${OUT}" "  {\"${name}\", R\"__json__(${content})__json__\"},\n")
endforeach()
file(APPEND "${OUT}"
  "};\nconst std::size_t kThemePresetCount = sizeof kThemePresets / sizeof kThemePresets[0];\n\n"
  "}  // namespace rolltui::embedded\n")
