# embed_presets.cmake — writes a C source embedding every file in FILES as a
# (name, contents) table, so the presets that SHIP are real files in the source tree
# (rolltui/presets/) that the editor may write, and are compiled in and parsed at
# start like the built-in layouts (plan/phase-9.md m11e, rule 5).
#
#   cmake -DOUT=<generated.c> -DTABLE=kThemePresets "-DFILES=<a.json;b.json>" \
#         [-DPREFIX=<prefix_>] -P embed_presets.cmake
# TABLE names the generated array; its count is <TABLE>Count with the trailing "s"
# dropped. PREFIX replaces what used to be a C++ NAMESPACE — a HOST embedding its own
# files (roll's presets/menus/, Phase 10 m3) passes its own so the two tables cannot
# collide.
#
# IT EMITS C, NOT C++, AND THE REASON IS A GAP THIS COST US (2026-09-04). These tables
# ARE the shipped presets — the ground truth every consumer parses — and they were
# `std::pair<std::string_view, std::string_view>` in a C++ namespace, reachable only
# from C++. When `rolltui-paint` was converted to the C API it could not read them, so
# it copied four scopes of `presets/bindings/default.json` into itself as a literal
# table: a fifth copy of a vocabulary, on the same day CLAUDE.md gained the rule
# forbidding exactly that. Data that every consumer needs must be reachable by every
# consumer; a table only one language can read is a table the other language will
# duplicate.
if(NOT DEFINED PREFIX)
  set(PREFIX "rolltui_")
endif()
string(REGEX REPLACE "s$" "" COUNT_NAME "${TABLE}")
file(WRITE "${OUT}"
  "/* generated by rolltui/cmake/embed_presets.cmake — do not edit */\n"
  "#include \"rolltui/c/rolltui_embedded.h\"\n\n"
  "const RolltuiEmbeddedFile ${PREFIX}${TABLE}[] = {\n")
foreach(f IN LISTS FILES)
  get_filename_component(name "${f}" NAME_WE)
  file(READ "${f}" content)
  file(APPEND "${OUT}" "  {\"${name}\", R\"__json__(${content})__json__\"},\n")
endforeach()
file(APPEND "${OUT}"
  "};\nconst size_t ${PREFIX}${COUNT_NAME}Count =\n"
  "    sizeof ${PREFIX}${TABLE} / sizeof ${PREFIX}${TABLE}[0];\n")
